### ISSUE TITLE
Unpin sphinx version?

### ISSUE THREAD

**Issue by OriolAbril** [astrojuanlu/copier-pylib#11]
I was a bit surprised to find

https://github.com/astrojuanlu/copier-pylib/blob/67833ed1684dec0689960afbca28fbecc3806f5e/template/pyproject.toml.j2#L44

is there a reason for this? furo, myst and copybutton all support newer versions without issues

**Comment by astrojuanlu** [comment]
Woops, it's a good point! IIRC we're at 6.x now, this got old quickly. I'm +1 on unpinning it
