### ISSUE TITLE
pydocstyle no longer used?

### ISSUE THREAD

**Issue by OriolAbril** [astrojuanlu/copier-pylib#12]
Not sure when it happened but pydocstyle check doesn't seem to be run anymore. IIUC, all checks are now run with pre-commit, and it doesn't appear there: https://github.com/astrojuanlu/copier-pylib/blob/main/template/.pre-commit-config.yaml. Is that a pending task from porting to pre-commit or is there a deeper reason?

**Comment by astrojuanlu** [comment]
Hmm weird, I can't find it in the old repo either, only in the README https://github.com/astrojuanlu/cookiecutter-pylib/ 

Let's restore it! http://www.pydocstyle.org/en/stable/usage.html#usage-with-the-pre-commit-git-hooks-framework
