### ISSUE TITLE
Switch from flit to PDM

### ISSUE THREAD

**Issue by astrojuanlu** [astrojuanlu/copier-pylib#17]
I've been using PDM lately for some new projects and I really like it.

Like flit, it has a `pdm init` command with a nice CLI wizard, it's standards-compliant, and largely transparent.

Unlike flit, it's extensible through plugins, has the ability of extracting the version from git, and does not rely on the `__version__` attribute, which I like (pretty much like the Pallets projects, I am migrating away from it https://github.com/getsentry/sentry-python/issues/2316)

Why not Pipenv? Because it's a 1st-generation workflow tool and we have collectively learned a lot from it. It tries to do too much, and badly. And unfortunately it has a cursed history IMHO (I prefer to stay away from [certain maintainers](https://kennethreitz.org/essays/why-im-not-collaborating-with-kenneth-reitz)).

Why not Poetry? Because, as a 2nd-generation tool that predates some packaging standards, it suffers from https://github.com/python-poetry/poetry/issues/3332. And their npm-esque way of specifying upper version caps is causing so much grief in the ecosystem.

Why not Hatch? Even as a 3rd-generation tool (very much like PDM), I don't like https://github.com/pypa/hatch/issues/507. I trust PDM much more.

Why not some 4th-generation tool, like rye or huak? Because they're still experimental.

**Comment by ofek** [comment]
For posterity, Hatch has supported building projects that use arbitrary backends since 1.8.0 https://hatch.pypa.io/latest/history/hatch/#hatch-v1.8.0
