### ISSUE TITLE
Consider reusing locally-installed linters in `pre-commit` 

### ISSUE THREAD

**Issue by astrojuanlu** [astrojuanlu/copier-pylib#6]
cc @antonymilneqb

**Comment by AntonyMilneQB** [comment]
Is this related? #1

**Comment by astrojuanlu** [comment]
Note that this integration might be a bit tricky or not possible, see https://cookiecutter-hypermodern-python.readthedocs.io/en/2020.11.15/guide.html#python-language-hooks

**Comment by astrojuanlu** [comment]
I once found a blog post that explained how pre-commit is a great tool to _execute_ linters, but so-so for _installing_ and _discovering_ them. Can't seem to locate it anymore.

**Comment by astrojuanlu** [comment]
https://github.com/OCA/oca-addons-repo-template/issues/175#issue-1466067857

**Comment by astrojuanlu** [comment]
I'm not doing any of this, at least for now.
