### ISSUE TITLE
Add test for pre-commit hooks or similar?

### ISSUE THREAD

**Issue by AntonyMilneQB** [astrojuanlu/copier-pylib#9]
To test #8 I did the following manually:
* make a test project using `copier template test`
* `validate-pyproject test/pyproject.toml`

Would it be valuable to have some sort of automated test that did something like this? More generally, should there be something to ensure that the baked test project adheres to the linting  standards that it comes with. e.g. maybe by running the pre-commit hooks against that project? (If you'd like to do `validate-pyproject` as a pre-commit hook, that's possible also.)

**Comment by astrojuanlu** [comment]
Yep, let's merge this with gh-3!
